### ISSUE TITLE
Compatibility with python 3?

### ISSUE THREAD

**Issue by daquang** [mblondel/svmlight-loader#9]
Can't seem to get this working on Python 3. Any help would be appreciated.

**Comment by hankliu5** [comment]
Because in Python 3, the C API for generating Python module changed. If you don't mind you might want to use my forked version: https://github.com/hankliu5/svmlight-loader

**Comment by mblondel** [comment]
Do you think conditional compilation would be a lot of work? (to support
both Python 2 and 3)

**Comment by hankliu5** [comment]
Shouldn’t be. There is a official Python document talking about how to use
macro to differentiate Python 2 and 3.

I would love to help but I’m busy recently. If you can wait, I can try to
finish that.

**Comment by mblondel** [comment]
Fixed by #10 .
